/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package charts

import (
	"path/filepath"

	"sigs.k8s.io/kubebuilder/v3/pkg/machinery"
)

var _ machinery.Template = &Chart{}

// Chart scaffolds a file that defines the kustomization scheme for the webhook folder
type Chart struct {
	machinery.TemplateMixin
	machinery.ProjectNameMixin
	machinery.RepositoryMixin
	Force bool
}

// SetTemplateDefaults implements file.Template
func (f *Chart) SetTemplateDefaults() error {
	if f.Path == "" {
		f.Path = filepath.Join("config", f.ProjectName, "Chart.yaml")
	}

	f.TemplateBody = chartTemplate

	if f.Force {
		f.IfExistsAction = machinery.OverwriteFile
	} else {
		// If file exists (ex. because a webhook was already created), skip creation.
		f.IfExistsAction = machinery.SkipFile
	}

	return nil
}

const chartTemplate = `apiVersion: v2
name: {{ .ProjectName }}
description: A Helm chart for Kubernetes auto generated by kubebuilder4helm
kubeVersion: "^1.22.0-0"
sources:
  - https://{{ .Repo }}
home: https://{{ .Repo }}
keywords:
  - {{ .ProjectName }}
type: application
version: 0.0.0
appVersion: "0.0.0"
`
